// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRIGvjpXRRmYq6xwrMyQakrPbnrNc4whQ',
    appId: '1:704126424461:web:2875acf26c2fe5e56a19c4',
    messagingSenderId: '704126424461',
    projectId: 'real-soft-b6c12',
    authDomain: 'real-soft-b6c12.firebaseapp.com',
    storageBucket: 'real-soft-b6c12.appspot.com',
    measurementId: 'G-VBSXBY2ECF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqhG7kDCFKJdKcz30561fel246fCdDsKM',
    appId: '1:704126424461:android:1436f7c8e5ce59dd6a19c4',
    messagingSenderId: '704126424461',
    projectId: 'real-soft-b6c12',
    storageBucket: 'real-soft-b6c12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzYTCeVdCf08P10GDStLorH1fz3ctELIo',
    appId: '1:704126424461:ios:cefcae103c7994a76a19c4',
    messagingSenderId: '704126424461',
    projectId: 'real-soft-b6c12',
    storageBucket: 'real-soft-b6c12.appspot.com',
    iosClientId: '704126424461-mq5sjavgevgcc3ioqg88s1831kq8tuvk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzYTCeVdCf08P10GDStLorH1fz3ctELIo',
    appId: '1:704126424461:ios:cefcae103c7994a76a19c4',
    messagingSenderId: '704126424461',
    projectId: 'real-soft-b6c12',
    storageBucket: 'real-soft-b6c12.appspot.com',
    iosClientId: '704126424461-mq5sjavgevgcc3ioqg88s1831kq8tuvk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
